apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: njxd1v10n-java-springboot
  janus-idp.io/tekton: njxd1v10n-java-springboot
  backstage.io/kubernetes-id: njxd1v10n-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: njxd1v10n-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
